Relocate related questions
StampyAI/stampy-ui pull request #245
Opened 2023-05-25 17:00 UTC by mruwnik

https://github.com/StampyAI/stampy-ui/issues/25

* when expanding a related question, move it below all other related questions (otherwise it just appears as a top level question with a random set of the parent question's related questions as its own related questions (too much recursion in that description...))
* pull in expanded related questions when opening a questions with related ones

2023-05-26 09:34 UTC, Aprillion requested changes

2023-05-26 09:34 UTC, Aprillion commented on app/hooks/stateModifiers.tsx
I'm afraid this still needs some UX improvements for questions with multiple related links like http://127.0.0.1:8787/?state=6178- .. opening one of the related links moves it below screen and also moves the parent question below screen, very confusing IMHO (especially when the parent is open and everything just jumps) .. not sure how to improve to correctly handle all important edge cases 😅 

<img src="https://github.com/StampyAI/stampy-ui/assets/1087670/93055374-a79d-4b56-ab56-9c12f111cdf8">

2023-05-26 13:51 UTC, mruwnik commented on app/hooks/stateModifiers.tsx
Totally agree with that. @ccstan99 @plexish any ideas how it should work?

2023-05-27 06:36 UTC, ccstan99 commented on app/hooks/stateModifiers.tsx
My initial thought is to have the related questions as a toggle list. 
- Only one list of related questions is open at any given time
- When a related question is selected, all the other related questions are collapsed into the toggle list.
There will be some unexpected movement and more bookkeeping of which questions are on screen & expanded, but we should be sure to scroll so the answer that was just recently expanded is in view. Unfortunately, I don't have access to image editing tools right now but can try to draw a diagram later if needed. 

I'm not loving this approach though. We might want to discuss further at the next dev call to see if there are other ideas and opinions before implementing.

Slightly separate issue based on what Aprillion pointed out: Do we really want an answer with 22 related questions now that we support tags? We might need a discussion on the philosophy behind related questions and how exhaustive vs suggestive they're intended to be.

2023-05-27 08:18 UTC, Aprillion commented on app/hooks/stateModifiers.tsx
I like the idea to scroll to the just-expanded answer and agree there should be fewer related questions per 1 parent.

If we move the next related question above the current parent, we might get away with the bookkeeping 🤔 it will look like the previous related questions are also related to the newly expanded parent, but that might be good enough for our "reading list" feature for now and we can complicate it later if needed 😅 

https://excalidraw.com/#room=b1392834d262e6d9a063,37R-5A0STeSAEaxqwmAg0A
![image](https://github.com/StampyAI/stampy-ui/assets/1087670/0ea59f58-5889-4a2b-9faa-fc81e78b011d)

2023-06-09 21:27 UTC, closed without merging