Use glossary table
StampyAI/stampy-ui pull request #278
Opened 2023-07-10 22:50 UTC by mruwnik

https://github.com/StampyAI/stampy-ui/issues/272
Uses the new [glossary table](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/Glossary_suZVl#Glossary_tujmw)

2023-07-10 22:51 UTC, mruwnik commented on app/routes/[sitemap.xml].tsx
> +      <loc>${origin}/?state=${pageid}${QuestionState.OPEN}</loc>
this has nothing to do with the glossary, but was needed to be done

2023-07-11 08:14 UTC, Aprillion requested changes

2023-07-11 09:11 UTC, mruwnik commented on app/server-utils/stampy.ts
> +    'question ID': string
UIID. The aliases can be empty - I'll update that bit

2023-07-11 09:19 UTC, Aprillion commented on app/server-utils/stampy.ts
> +    'question ID': string
I mean, why a new field and why not using the existing "UI ID" field if it's the same table shape type?

2023-07-11 10:39 UTC, Aprillion reviewed
looks better now 👍 

discriminating union with runtime assertions would be even better to make sure we get what we expect instead of just trusting Coda and doing type assertions, but that can be improved later

2023-07-11 10:39 UTC, Aprillion commented on app/routes/questions/$question.tsx
> +        console.log(entry)
forgotten log?

2023-07-11 11:22 UTC, Aprillion approved these changes

2023-07-11 11:23 UTC, merged