Stampy redesign
StampyAI/stampy-ui pull request #543
Opened 2024-03-08 17:33 UTC by mruwnik

QA here: https://redesign.aprillion.workers.dev

2024-03-09 00:49 UTC, melissasamworth requested changes
I have two launch-blocking issues
<img width="361" alt="image" src="https://github.com/StampyAI/stampy-ui/assets/825910/b73b979d-7425-4ba1-9a84-3b7c0f27b987">

2024-03-09 07:26 UTC, Aprillion commented on README.md
@mruwnik / @buddy-web3  could you update README, please? this was not the only change, right? 🤔

2024-03-10 08:56 UTC, Aprillion reviewed
...I checked a few files and I don't have any big objections. The site after redesign was supposed to be more professional than the old one, so I am not sure about releasing before fixing most of the small bugs too and cleaning up code for unused features or whatever is still duplicated, and updating README and/or other documentation ... but I will leave that up the core team. I can help after 2024-03-30 to do more polishing even after release I guess.

FTR, https://www.aisafety.com/reading-guide is now updated to use iframe from `stampy.ai` and DNS in Cloudflare is updated to point stampy.ai to https://stampy-ui.aprillion.workers.dev/ => migration of embed version is not a blocker any more.

2024-03-18 13:08 UTC, melissasamworth approved these changes

2024-03-18 13:08 UTC, merged