Stampy redesign 591
StampyAI/stampy-ui pull request #602
Opened 2024-04-30 02:39 UTC by buddy-web3

#591 #590

2024-04-30 21:41 UTC, melissasamworth requested changes

2024-04-30 21:41 UTC, melissasamworth commented on app/components/Chatbot/index.tsx
> +    <div className="centered col-9 height-70">
I believe this should take up 10 columns
<img width="946" alt="image" src="https://github.com/StampyAI/stampy-ui/assets/825910/cfbb088e-2d8a-4067-ae4d-44bf97395aaf">

2024-04-30 21:41 UTC, melissasamworth commented on app/components/Chatbot/index.tsx
> +    <div className="centered col-9 height-70">
If you want to leave this to me when I do css that's totally fine

2024-04-30 21:41 UTC, melissasamworth commented on app/components/Chatbot/widgit.css
> +.height-70 {
oh interesting. For now on we could do .height-70vh so we know the units!

2024-04-30 21:41 UTC, melissasamworth commented on app/components/Chatbot/widgit.css
> +  color: #d40000;
We'll want to define this and reference it as a variable, plus put this class in the same place as the other color classes in root.css

2024-04-30 21:41 UTC, melissasamworth commented on app/components/Nav/index.tsx
> +            text="Stampy chatbot"
This is the global nav right? Could we make it say "AI Safety chatbot" instead? :)

2024-05-01 01:27 UTC, buddy-web3 commented
@melissasamworth "If you want to leave this to me when I do css that's totally fine" - yes please, take over the design parts. Please note that all of those are unrelated to the tickets.. they are some design changes that I had stashed and now somehow got pushed.

2024-05-01 18:13 UTC, melissasamworth approved these changes

2024-05-01 18:13 UTC, merged